set up webpack
Charming-Chanterelle/Shop_with_Rob pull request #2
Opened 2021-09-09 07:57 UTC by bry-beep

2021-09-09 17:49 UTC, juanVmejia requested changes
Great webpack

2021-09-09 18:03 UTC, juanVmejia approved these changes

2021-09-09 18:04 UTC, juanVmejia commented
GREAT JOB 👏

2021-09-09 18:04 UTC, merged

2021-09-15 19:26 UTC, rolopez23 commented
Remember spend some time looking at PRS! The goal is not to rubber stamp but to make sure it is right (in a collaberative growing way). Here the large number of files is a warning that pieces were not being gitignored and there is a problem looming.